-- SGN_CIRCULAR: Ana tablo - PDF bilgileri ve firma eşleşmesi
CREATE TABLE SGN_CIRCULAR (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FIRMA_UNVANI NVARCHAR(200) NOT NULL,
    FIRMA_HESAP_NUMARASI NVARCHAR(50),
    IMZA_SIRKULERI_DUZENLEME_TARIHI DATE,
    IMZA_SIRKULERI_GECERLILIK_TARIHI DATE,
    SURESIZ_GECERLI BIT DEFAULT 0,
    OZEL_DURUMLAR NVARCHAR(MAX),
    NOTER_IMZA_SIRKULERI_NO NVARCHAR(50),
    IMZA_SIRKULERI_GORUNTUSU NVARCHAR(250), -- PDF dosya yolu
    AKTIF_PASIF BIT DEFAULT 1,
    ACIKLAMA NVARCHAR(MAX),
    KULLANICI NVARCHAR(100),
    KAYIT_TARIHI DATETIME DEFAULT GETDATE(),
    GUNCELLEME_TARIHI DATETIME
);

-- SGN_CIRCULARDETAIL: Seçilen imzacıların bilgileri
CREATE TABLE SGN_CIRCULARDETAIL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SGN_CIRCULAR_ID INT NOT NULL,
    ADI_SOYADI NVARCHAR(150) NOT NULL,
    YETKI_SEKLI NVARCHAR(100),
    YETKI_SURE NVARCHAR(100),
    YETKI_BITIS_TARIHI DATE,
    IMZA_YETKI_GRUBU NVARCHAR(100),
    SINIRLI_YETKI_VAR_MI BIT DEFAULT 0,
    YETKI_OLDUGU_ISLEMLER NVARCHAR(MAX),
    IMZA_GORUNTUSU NVARCHAR(250), -- Seçilen imza görüntüsü koordinatları/yolu
    IMZA_KOORDINAT_X INT,
    IMZA_KOORDINAT_Y INT,
    IMZA_KOORDINAT_WIDTH INT,
    IMZA_KOORDINAT_HEIGHT INT,
    AKTIF_PASIF BIT DEFAULT 1,
    KAYIT_TARIHI DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (SGN_CIRCULAR_ID) REFERENCES SGN_CIRCULAR(ID)
);

-- SGN_OPERATION: İşlem türleri
CREATE TABLE SGN_OPERATION (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SGN_CIRCULAR_ID INT NOT NULL,
    OPERATION_TYPE NVARCHAR(100) NOT NULL,
    OPERATION_CODE NVARCHAR(20),
    ACIKLAMA NVARCHAR(255),
    AKTIF_PASIF BIT DEFAULT 1,
    KAYIT_TARIHI DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (SGN_CIRCULAR_ID) REFERENCES SGN_CIRCULAR(ID)
);

-- SGN_ROLETYPE: Yetki türleri ve grupları
CREATE TABLE SGN_ROLETYPE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SGN_CIRCULAR_ID INT NOT NULL,
    ROLE_GROUP NVARCHAR(50) NOT NULL, -- A GRUBU, B GRUBU, C GRUBU, etc.
    ROLE_TYPE NVARCHAR(100) NOT NULL, -- 1. DERECE İMZA YETKİLİSİ, etc.
    MIN_SIGNATURE_COUNT INT DEFAULT 1,
    MAX_SIGNATURE_COUNT INT,
    YETKI_LIMITI DECIMAL(18,2),
    PARA_BIRIMI NVARCHAR(10),
    ACIKLAMA NVARCHAR(255),
    AKTIF_PASIF BIT DEFAULT 1,
    KAYIT_TARIHI DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (SGN_CIRCULAR_ID) REFERENCES SGN_CIRCULAR(ID)
);

-- İndeksler
CREATE INDEX IX_SGN_CIRCULARDETAIL_CIRCULAR_ID ON SGN_CIRCULARDETAIL(SGN_CIRCULAR_ID);
CREATE INDEX IX_SGN_OPERATION_CIRCULAR_ID ON SGN_OPERATION(SGN_CIRCULAR_ID);
CREATE INDEX IX_SGN_ROLETYPE_CIRCULAR_ID ON SGN_ROLETYPE(SGN_CIRCULAR_ID);
CREATE INDEX IX_SGN_CIRCULAR_FIRMA ON SGN_CIRCULAR(FIRMA_UNVANI); 