-- =============================================
-- SGN_CIRCULAR Stored Procedures
-- =============================================

-- INSERT
CREATE PROCEDURE SGN_CIRCULAR_INS_SP
    @FIRMA_UNVANI NVARCHAR(200),
    @FIRMA_HESAP_NUMARASI NVARCHAR(50) = NULL,
    @IMZA_SIRKULERI_DUZENLEME_TARIHI DATE = NULL,
    @IMZA_SIRKULERI_GECERLILIK_TARIHI DATE = NULL,
    @SURESIZ_GECERLI BIT = 0,
    @OZEL_DURUMLAR NVARCHAR(MAX) = NULL,
    @NOTER_IMZA_SIRKULERI_NO NVARCHAR(50) = NULL,
    @IMZA_SIRKULERI_GORUNTUSU NVARCHAR(250) = NULL,
    @ACIKLAMA NVARCHAR(MAX) = NULL,
    @KULLANICI NVARCHAR(100) = NULL,
    @NEW_ID INT OUTPUT
AS
BEGIN
    INSERT INTO SGN_CIRCULAR (
        FIRMA_UNVANI, FIRMA_HESAP_NUMARASI, IMZA_SIRKULERI_DUZENLEME_TARIHI,
        IMZA_SIRKULERI_GECERLILIK_TARIHI, SURESIZ_GECERLI, OZEL_DURUMLAR,
        NOTER_IMZA_SIRKULERI_NO, IMZA_SIRKULERI_GORUNTUSU, ACIKLAMA, KULLANICI
    )
    VALUES (
        @FIRMA_UNVANI, @FIRMA_HESAP_NUMARASI, @IMZA_SIRKULERI_DUZENLEME_TARIHI,
        @IMZA_SIRKULERI_GECERLILIK_TARIHI, @SURESIZ_GECERLI, @OZEL_DURUMLAR,
        @NOTER_IMZA_SIRKULERI_NO, @IMZA_SIRKULERI_GORUNTUSU, @ACIKLAMA, @KULLANICI
    );
    
    SET @NEW_ID = SCOPE_IDENTITY();
END
GO

-- UPDATE
CREATE PROCEDURE SGN_CIRCULAR_UPD_SP
    @ID INT,
    @FIRMA_UNVANI NVARCHAR(200),
    @FIRMA_HESAP_NUMARASI NVARCHAR(50) = NULL,
    @IMZA_SIRKULERI_DUZENLEME_TARIHI DATE = NULL,
    @IMZA_SIRKULERI_GECERLILIK_TARIHI DATE = NULL,
    @SURESIZ_GECERLI BIT = 0,
    @OZEL_DURUMLAR NVARCHAR(MAX) = NULL,
    @NOTER_IMZA_SIRKULERI_NO NVARCHAR(50) = NULL,
    @IMZA_SIRKULERI_GORUNTUSU NVARCHAR(250) = NULL,
    @AKTIF_PASIF BIT = 1,
    @ACIKLAMA NVARCHAR(MAX) = NULL,
    @KULLANICI NVARCHAR(100) = NULL
AS
BEGIN
    UPDATE SGN_CIRCULAR 
    SET 
        FIRMA_UNVANI = @FIRMA_UNVANI,
        FIRMA_HESAP_NUMARASI = @FIRMA_HESAP_NUMARASI,
        IMZA_SIRKULERI_DUZENLEME_TARIHI = @IMZA_SIRKULERI_DUZENLEME_TARIHI,
        IMZA_SIRKULERI_GECERLILIK_TARIHI = @IMZA_SIRKULERI_GECERLILIK_TARIHI,
        SURESIZ_GECERLI = @SURESIZ_GECERLI,
        OZEL_DURUMLAR = @OZEL_DURUMLAR,
        NOTER_IMZA_SIRKULERI_NO = @NOTER_IMZA_SIRKULERI_NO,
        IMZA_SIRKULERI_GORUNTUSU = @IMZA_SIRKULERI_GORUNTUSU,
        AKTIF_PASIF = @AKTIF_PASIF,
        ACIKLAMA = @ACIKLAMA,
        KULLANICI = @KULLANICI,
        GUNCELLEME_TARIHI = GETDATE()
    WHERE ID = @ID;
END
GO

-- SELECT
CREATE PROCEDURE SGN_CIRCULAR_SEL_SP
    @ID INT = NULL
AS
BEGIN
    SELECT * FROM SGN_CIRCULAR
    WHERE (@ID IS NULL OR ID = @ID)
    AND AKTIF_PASIF = 1
    ORDER BY KAYIT_TARIHI DESC;
END
GO

-- DELETE (Soft Delete)
CREATE PROCEDURE SGN_CIRCULAR_DEL_SP
    @ID INT
AS
BEGIN
    UPDATE SGN_CIRCULAR 
    SET AKTIF_PASIF = 0, GUNCELLEME_TARIHI = GETDATE()
    WHERE ID = @ID;
END
GO

-- =============================================
-- SGN_CIRCULARDETAIL Stored Procedures
-- =============================================

-- INSERT
CREATE PROCEDURE SGN_CIRCULARDETAIL_INS_SP
    @SGN_CIRCULAR_ID INT,
    @ADI_SOYADI NVARCHAR(150),
    @YETKI_SEKLI NVARCHAR(100) = NULL,
    @YETKI_SURE NVARCHAR(100) = NULL,
    @YETKI_BITIS_TARIHI DATE = NULL,
    @IMZA_YETKI_GRUBU NVARCHAR(100) = NULL,
    @SINIRLI_YETKI_VAR_MI BIT = 0,
    @YETKI_OLDUGU_ISLEMLER NVARCHAR(MAX) = NULL,
    @IMZA_GORUNTUSU NVARCHAR(250) = NULL,
    @IMZA_KOORDINAT_X INT = NULL,
    @IMZA_KOORDINAT_Y INT = NULL,
    @IMZA_KOORDINAT_WIDTH INT = NULL,
    @IMZA_KOORDINAT_HEIGHT INT = NULL,
    @NEW_ID INT OUTPUT
AS
BEGIN
    INSERT INTO SGN_CIRCULARDETAIL (
        SGN_CIRCULAR_ID, ADI_SOYADI, YETKI_SEKLI, YETKI_SURE, YETKI_BITIS_TARIHI,
        IMZA_YETKI_GRUBU, SINIRLI_YETKI_VAR_MI, YETKI_OLDUGU_ISLEMLER,
        IMZA_GORUNTUSU, IMZA_KOORDINAT_X, IMZA_KOORDINAT_Y, 
        IMZA_KOORDINAT_WIDTH, IMZA_KOORDINAT_HEIGHT
    )
    VALUES (
        @SGN_CIRCULAR_ID, @ADI_SOYADI, @YETKI_SEKLI, @YETKI_SURE, @YETKI_BITIS_TARIHI,
        @IMZA_YETKI_GRUBU, @SINIRLI_YETKI_VAR_MI, @YETKI_OLDUGU_ISLEMLER,
        @IMZA_GORUNTUSU, @IMZA_KOORDINAT_X, @IMZA_KOORDINAT_Y, 
        @IMZA_KOORDINAT_WIDTH, @IMZA_KOORDINAT_HEIGHT
    );
    
    SET @NEW_ID = SCOPE_IDENTITY();
END
GO

-- UPDATE
CREATE PROCEDURE SGN_CIRCULARDETAIL_UPD_SP
    @ID INT,
    @SGN_CIRCULAR_ID INT,
    @ADI_SOYADI NVARCHAR(150),
    @YETKI_SEKLI NVARCHAR(100) = NULL,
    @YETKI_SURE NVARCHAR(100) = NULL,
    @YETKI_BITIS_TARIHI DATE = NULL,
    @IMZA_YETKI_GRUBU NVARCHAR(100) = NULL,
    @SINIRLI_YETKI_VAR_MI BIT = 0,
    @YETKI_OLDUGU_ISLEMLER NVARCHAR(MAX) = NULL,
    @IMZA_GORUNTUSU NVARCHAR(250) = NULL,
    @IMZA_KOORDINAT_X INT = NULL,
    @IMZA_KOORDINAT_Y INT = NULL,
    @IMZA_KOORDINAT_WIDTH INT = NULL,
    @IMZA_KOORDINAT_HEIGHT INT = NULL,
    @AKTIF_PASIF BIT = 1
AS
BEGIN
    UPDATE SGN_CIRCULARDETAIL 
    SET 
        SGN_CIRCULAR_ID = @SGN_CIRCULAR_ID,
        ADI_SOYADI = @ADI_SOYADI,
        YETKI_SEKLI = @YETKI_SEKLI,
        YETKI_SURE = @YETKI_SURE,
        YETKI_BITIS_TARIHI = @YETKI_BITIS_TARIHI,
        IMZA_YETKI_GRUBU = @IMZA_YETKI_GRUBU,
        SINIRLI_YETKI_VAR_MI = @SINIRLI_YETKI_VAR_MI,
        YETKI_OLDUGU_ISLEMLER = @YETKI_OLDUGU_ISLEMLER,
        IMZA_GORUNTUSU = @IMZA_GORUNTUSU,
        IMZA_KOORDINAT_X = @IMZA_KOORDINAT_X,
        IMZA_KOORDINAT_Y = @IMZA_KOORDINAT_Y,
        IMZA_KOORDINAT_WIDTH = @IMZA_KOORDINAT_WIDTH,
        IMZA_KOORDINAT_HEIGHT = @IMZA_KOORDINAT_HEIGHT,
        AKTIF_PASIF = @AKTIF_PASIF
    WHERE ID = @ID;
END
GO

-- SELECT
CREATE PROCEDURE SGN_CIRCULARDETAIL_SEL_SP
    @ID INT = NULL,
    @SGN_CIRCULAR_ID INT = NULL
AS
BEGIN
    SELECT * FROM SGN_CIRCULARDETAIL
    WHERE (@ID IS NULL OR ID = @ID)
    AND (@SGN_CIRCULAR_ID IS NULL OR SGN_CIRCULAR_ID = @SGN_CIRCULAR_ID)
    AND AKTIF_PASIF = 1
    ORDER BY KAYIT_TARIHI DESC;
END
GO

-- DELETE
CREATE PROCEDURE SGN_CIRCULARDETAIL_DEL_SP
    @ID INT
AS
BEGIN
    UPDATE SGN_CIRCULARDETAIL 
    SET AKTIF_PASIF = 0
    WHERE ID = @ID;
END
GO

-- =============================================
-- SGN_OPERATION Stored Procedures
-- =============================================

-- INSERT
CREATE PROCEDURE SGN_OPERATION_INS_SP
    @SGN_CIRCULAR_ID INT,
    @OPERATION_TYPE NVARCHAR(100),
    @OPERATION_CODE NVARCHAR(20) = NULL,
    @ACIKLAMA NVARCHAR(255) = NULL,
    @NEW_ID INT OUTPUT
AS
BEGIN
    INSERT INTO SGN_OPERATION (SGN_CIRCULAR_ID, OPERATION_TYPE, OPERATION_CODE, ACIKLAMA)
    VALUES (@SGN_CIRCULAR_ID, @OPERATION_TYPE, @OPERATION_CODE, @ACIKLAMA);
    
    SET @NEW_ID = SCOPE_IDENTITY();
END
GO

-- UPDATE
CREATE PROCEDURE SGN_OPERATION_UPD_SP
    @ID INT,
    @SGN_CIRCULAR_ID INT,
    @OPERATION_TYPE NVARCHAR(100),
    @OPERATION_CODE NVARCHAR(20) = NULL,
    @ACIKLAMA NVARCHAR(255) = NULL,
    @AKTIF_PASIF BIT = 1
AS
BEGIN
    UPDATE SGN_OPERATION 
    SET 
        SGN_CIRCULAR_ID = @SGN_CIRCULAR_ID,
        OPERATION_TYPE = @OPERATION_TYPE,
        OPERATION_CODE = @OPERATION_CODE,
        ACIKLAMA = @ACIKLAMA,
        AKTIF_PASIF = @AKTIF_PASIF
    WHERE ID = @ID;
END
GO

-- SELECT
CREATE PROCEDURE SGN_OPERATION_SEL_SP
    @ID INT = NULL,
    @SGN_CIRCULAR_ID INT = NULL
AS
BEGIN
    SELECT * FROM SGN_OPERATION
    WHERE (@ID IS NULL OR ID = @ID)
    AND (@SGN_CIRCULAR_ID IS NULL OR SGN_CIRCULAR_ID = @SGN_CIRCULAR_ID)
    AND AKTIF_PASIF = 1
    ORDER BY KAYIT_TARIHI DESC;
END
GO

-- DELETE
CREATE PROCEDURE SGN_OPERATION_DEL_SP
    @ID INT
AS
BEGIN
    UPDATE SGN_OPERATION 
    SET AKTIF_PASIF = 0
    WHERE ID = @ID;
END
GO

-- =============================================
-- SGN_ROLETYPE Stored Procedures
-- =============================================

-- INSERT
CREATE PROCEDURE SGN_ROLETYPE_INS_SP
    @SGN_CIRCULAR_ID INT,
    @ROLE_GROUP NVARCHAR(50),
    @ROLE_TYPE NVARCHAR(100),
    @MIN_SIGNATURE_COUNT INT = 1,
    @MAX_SIGNATURE_COUNT INT = NULL,
    @YETKI_LIMITI DECIMAL(18,2) = NULL,
    @PARA_BIRIMI NVARCHAR(10) = NULL,
    @ACIKLAMA NVARCHAR(255) = NULL,
    @NEW_ID INT OUTPUT
AS
BEGIN
    INSERT INTO SGN_ROLETYPE (
        SGN_CIRCULAR_ID, ROLE_GROUP, ROLE_TYPE, MIN_SIGNATURE_COUNT,
        MAX_SIGNATURE_COUNT, YETKI_LIMITI, PARA_BIRIMI, ACIKLAMA
    )
    VALUES (
        @SGN_CIRCULAR_ID, @ROLE_GROUP, @ROLE_TYPE, @MIN_SIGNATURE_COUNT,
        @MAX_SIGNATURE_COUNT, @YETKI_LIMITI, @PARA_BIRIMI, @ACIKLAMA
    );
    
    SET @NEW_ID = SCOPE_IDENTITY();
END
GO

-- UPDATE
CREATE PROCEDURE SGN_ROLETYPE_UPD_SP
    @ID INT,
    @SGN_CIRCULAR_ID INT,
    @ROLE_GROUP NVARCHAR(50),
    @ROLE_TYPE NVARCHAR(100),
    @MIN_SIGNATURE_COUNT INT = 1,
    @MAX_SIGNATURE_COUNT INT = NULL,
    @YETKI_LIMITI DECIMAL(18,2) = NULL,
    @PARA_BIRIMI NVARCHAR(10) = NULL,
    @ACIKLAMA NVARCHAR(255) = NULL,
    @AKTIF_PASIF BIT = 1
AS
BEGIN
    UPDATE SGN_ROLETYPE 
    SET 
        SGN_CIRCULAR_ID = @SGN_CIRCULAR_ID,
        ROLE_GROUP = @ROLE_GROUP,
        ROLE_TYPE = @ROLE_TYPE,
        MIN_SIGNATURE_COUNT = @MIN_SIGNATURE_COUNT,
        MAX_SIGNATURE_COUNT = @MAX_SIGNATURE_COUNT,
        YETKI_LIMITI = @YETKI_LIMITI,
        PARA_BIRIMI = @PARA_BIRIMI,
        ACIKLAMA = @ACIKLAMA,
        AKTIF_PASIF = @AKTIF_PASIF
    WHERE ID = @ID;
END
GO

-- SELECT
CREATE PROCEDURE SGN_ROLETYPE_SEL_SP
    @ID INT = NULL,
    @SGN_CIRCULAR_ID INT = NULL
AS
BEGIN
    SELECT * FROM SGN_ROLETYPE
    WHERE (@ID IS NULL OR ID = @ID)
    AND (@SGN_CIRCULAR_ID IS NULL OR SGN_CIRCULAR_ID = @SGN_CIRCULAR_ID)
    AND AKTIF_PASIF = 1
    ORDER BY KAYIT_TARIHI DESC;
END
GO

-- DELETE
CREATE PROCEDURE SGN_ROLETYPE_DEL_SP
    @ID INT
AS
BEGIN
    UPDATE SGN_ROLETYPE 
    SET AKTIF_PASIF = 0
    WHERE ID = @ID;
END
GO 